# fly.toml app configuration file generated for postgres-long-sound-439-dev on 2025-07-13T21:36:26+09:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'postgres-long-sound-439-dev'
primary_region = 'hkg'

[build]

[[mounts]]
  source = 'pg_data_dev'
  destination = '/var/lib/postgresql/data'

[http_service]
  internal_port = 5432
  force_https = true
  auto_stop_machines = false 
  auto_start_machines = false 
  min_machines_running = 1

[[vm]]
  size = 'shared-cpu-1x'
