# PRｋクローズにプレビューアプリを削除する
name: Delete Review App
on:
  # プルリクイベントで発動
  pull_request:
    types: [closed]

jobs:
  review_app:
    runs-on: ubuntu-latest
    outputs:
      url: ${{ steps.deploy.outputs.url }}
    # キーを指定して並行処理を制御
    concurrency:
      group: pr-${{ github.event.number }}
      # 同じPRの並行処理をキャンセル
      cancel-in-progress: true

    env:
      FLY_API_TOKEN: ${{ secrets.FLY_ORGANIZATION_TOKEN }}
      FLY_REGION: nrt
      FLY_ORG: personal
      DATABASE_URL: ${{ secrets.DATABASE_URL }}
    steps:
      - name: Install Fly
        run: |
          curl -L https://fly.io/install.sh | sh
          echo "$HOME/.fly/bin" >> $GITHUB_PATH

      - uses: actions/checkout@v4

      - name: Destroy Fly.io app
        working-directory: ./backend
        run: fly apps destroy --yes pr-${{ github.event.number }}-tmp-app
