# PR作成時に branch-name.domain.com でアプリをデプロイするGitHub Actions
# https://fly.io/docs/blueprints/review-apps-guide/
name: Deploy Review App
on:
  # プルリクイベントで発動
  pull_request:
    types: [opened, reopened, synchronize]

jobs:
  review_app:
    runs-on: ubuntu-latest
    outputs:
      url: ${{ steps.deploy.outputs.url }}
    # キーを指定して並行処理を制御
    concurrency:
      group: pr-${{ github.event.number }}
      # 同じPRの並行処理をキャンセル
      cancel-in-progress: true

    env:
      FLY_API_TOKEN: ${{ secrets.FLY_ORGANIZATION_TOKEN }}
      FLY_REGION: nrt
      FLY_ORG: personal
      DATABASE_URL: ${{ secrets.DATABASE_URL }}
    steps:
      - name: Get code
        uses: actions/checkout@v4

      - name: Install Fly
        run: |
          curl -L https://fly.io/install.sh | sh
          echo "$HOME/.fly/bin" >> $GITHUB_PATH

      - name: Check fly version
        run: fly version

      - name: Determine App Name
        id: vars
        run: echo "APP_NAME=pr-${{ github.event.number }}-tmp-app" >> $GITHUB_ENV

      - name: Create app
        run: fly apps create $APP_NAME --org $FLY_ORG --region $FLY_REGION --no-deploy

      - name: Set Secrets
        run: fly secrets set DATABASE_URL="${{ secrets.DATABASE_URL }}" -a $APP_NAME

      - name: Deploy
        working-directory: ./backend
        run: fly deploy --remote --app $APP_NAME
